# Generated by Django 4.2.3 on 2023-07-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_foodmodel_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='description_image',
            field=models.ImageField(null=True, upload_to='products_description', verbose_name='description'),
        ),
    ]
