# Generated by Django 4.2.3 on 2023-07-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_foodmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='ru_description',
            field=models.TextField(blank=True, null=True, verbose_name='ru_description'),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='uz_description',
            field=models.TextField(blank=True, null=True, verbose_name='uz_description'),
        ),
    ]
