# Generated by Django 4.2.3 on 2023-07-31 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_status_cartitem_cart_status_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
