# Generated by Django 4.2.3 on 2023-08-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_cart_status_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('submitted', 'Отправлена'), ('processed', 'Обработана'), ('shipped', 'Отправлена'), ('delivered', 'Доставлена')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
