# Generated by Django 4.2.3 on 2023-08-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart_status_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('submitted', 'Отправлена'), ('processed', 'Обработана'), ('shipped', 'Отправлена'), ('delivered', 'Доставлена')], default='active', max_length=20),
        ),
    ]
