# Generated by Django 4.2.3 on 2023-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('order', 'Заказ'), ('processing', 'Обработка'), ('cooking', 'Готовка'), ('shipped', 'Отправлена'), ('delivered', 'Доставлена')], default='active', max_length=20),
        ),
    ]
