# Generated by Django 4.2.3 on 2023-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_cart_address_cart_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.CharField(blank=True, default='none', max_length=128),
        ),
        migrations.AlterField(
            model_name='cart',
            name='phone',
            field=models.CharField(blank=True, default='none', max_length=13),
        ),
    ]
