# Generated by Django 4.2.3 on 2023-08-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_cart_review_cart_total_price_alter_cart_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('order', 'Заказ'), ('processing', 'Обработка'), ('cooking', 'Готовка'), ('shipped', 'Отправлена'), ('delivered', 'Доставлена'), ('not_active', 'Не активен')], default='order', max_length=20),
        ),
    ]
