# Generated by Django 4.2.3 on 2023-08-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_promocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
